spring.main.allow-circular-references=true
spring.application.name=journal
spring.mongodb.uri=mongodb+srv://0xkishan:asdasfasf@reise.soevadu.mongodb.net/?appName=reise
spring.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true